
secret:
  dbPassword: am9obmFobg==
  name: db-secret
  key: DB_Password
 
image:
  repository: lordofkangs/k8s_mysql
  tag: 16

service:
  name: mysql
  protocol: TCP
  type: ClusterIP
  port: 3306
  targetPort: 3306

deployment:
  replicaCount: 1
  containerPort: 3306
  envPwName: MYSQL_ROOT_PASSWORD
  envDbName: MYSQL_DATABASE
  envDbValue: myapp
  
  




