apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    prometheus.io/scrape: {{ .Values.service.scrape }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
   app: {{ .Chart.Name }}
   
