apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
      prometheus.io/scrape: true
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
   app: {{ .Chart.Name }}
   
