

replicaCount: 2
containerPort: 3000

image:
  repository: lordofkangs/react_frontend
  tag: ""


service:
  protocol: TCP
  type: ClusterIP
  port: 80
  targetPort: 3000


ingress:
  name: nginx-ingress
  pathType: Prefix
  frontPath: /
  frontService: react-frontend
  frontPort: 80
  backPath: /api
  backService: nodejs-backend
  backPort: 8080
  




