apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
      http:
        paths:
          - path: {{ .Values.ingress.frontPath }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.ingress.frontService }}
                port:
                  number: {{ .Values.ingress.frontPort }}
          - path: {{ .Values.ingress.backPath }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.ingress.backService }}
                port:
                  number: {{ .Values.ingress.backPort }}
